//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class SendStatusRequest : Message
    {
        public const string k_RosMessageName = "obr_msgs/SendStatus";
        public override string RosMessageName => k_RosMessageName;

        public sbyte mission_status;
        public sbyte direction_request;
        public bool estop_request;

        public SendStatusRequest()
        {
            this.mission_status = 0;
            this.direction_request = 0;
            this.estop_request = false;
        }

        public SendStatusRequest(sbyte mission_status, sbyte direction_request, bool estop_request)
        {
            this.mission_status = mission_status;
            this.direction_request = direction_request;
            this.estop_request = estop_request;
        }

        public static SendStatusRequest Deserialize(MessageDeserializer deserializer) => new SendStatusRequest(deserializer);

        private SendStatusRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mission_status);
            deserializer.Read(out this.direction_request);
            deserializer.Read(out this.estop_request);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mission_status);
            serializer.Write(this.direction_request);
            serializer.Write(this.estop_request);
        }

        public override string ToString()
        {
            return "SendStatusRequest: " +
            "\nmission_status: " + mission_status.ToString() +
            "\ndirection_request: " + direction_request.ToString() +
            "\nestop_request: " + estop_request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
