//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class SetEventRequest : Message
    {
        public const string k_RosMessageName = "obr_msgs/SetEvent";
        public override string RosMessageName => k_RosMessageName;

        public byte @event;
        public const byte NOT_SELECTED = 0;
        public const byte ACCELERATION = 1;
        public const byte SKIDPAD = 2;
        public const byte AUTOCROSS = 3;
        public const byte TRACK_DRIVE = 4;
        public const byte STATIC_INSPECTION_A = 5;
        public const byte STATIC_INSPECTION_B = 6;
        public const byte AUTONOMOUS_DEMO = 7;

        public SetEventRequest()
        {
            this.@event = 0;
        }

        public SetEventRequest(byte @event)
        {
            this.@event = @event;
        }

        public static SetEventRequest Deserialize(MessageDeserializer deserializer) => new SetEventRequest(deserializer);

        private SetEventRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@event);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@event);
        }

        public override string ToString()
        {
            return "SetEventRequest: " +
            "\n@event: " + @event.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
