//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class SetStateRequest : Message
    {
        public const string k_RosMessageName = "obr_msgs/SetState";
        public override string RosMessageName => k_RosMessageName;

        public StateMsg state;

        public SetStateRequest()
        {
            this.state = new StateMsg();
        }

        public SetStateRequest(StateMsg state)
        {
            this.state = state;
        }

        public static SetStateRequest Deserialize(MessageDeserializer deserializer) => new SetStateRequest(deserializer);

        private SetStateRequest(MessageDeserializer deserializer)
        {
            this.state = StateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "SetStateRequest: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
