//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class ToggleLapcountResponse : Message
    {
        public const string k_RosMessageName = "obr_msgs/ToggleLapcount";
        public override string RosMessageName => k_RosMessageName;

        public bool state;

        public ToggleLapcountResponse()
        {
            this.state = false;
        }

        public ToggleLapcountResponse(bool state)
        {
            this.state = state;
        }

        public static ToggleLapcountResponse Deserialize(MessageDeserializer deserializer) => new ToggleLapcountResponse(deserializer);

        private ToggleLapcountResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "ToggleLapcountResponse: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
