//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AdsDv
{
    [Serializable]
    public class AI2VCUDriveRMsg : Message
    {
        public const string k_RosMessageName = "ads_dv_msgs/AI2VCUDriveR";
        public override string RosMessageName => k_RosMessageName;

        //  Requested rear axle torque [0 - 195] Nm
        public ushort rear_axle_trq_request_nm;
        //  Rear motor speed limit [0 - 4000] rpm
        public ushort rear_motor_speed_max_rpm;

        public AI2VCUDriveRMsg()
        {
            this.rear_axle_trq_request_nm = 0;
            this.rear_motor_speed_max_rpm = 0;
        }

        public AI2VCUDriveRMsg(ushort rear_axle_trq_request_nm, ushort rear_motor_speed_max_rpm)
        {
            this.rear_axle_trq_request_nm = rear_axle_trq_request_nm;
            this.rear_motor_speed_max_rpm = rear_motor_speed_max_rpm;
        }

        public static AI2VCUDriveRMsg Deserialize(MessageDeserializer deserializer) => new AI2VCUDriveRMsg(deserializer);

        private AI2VCUDriveRMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.rear_axle_trq_request_nm);
            deserializer.Read(out this.rear_motor_speed_max_rpm);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rear_axle_trq_request_nm);
            serializer.Write(this.rear_motor_speed_max_rpm);
        }

        public override string ToString()
        {
            return "AI2VCUDriveRMsg: " +
            "\nrear_axle_trq_request_nm: " + rear_axle_trq_request_nm.ToString() +
            "\nrear_motor_speed_max_rpm: " + rear_motor_speed_max_rpm.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
