//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AdsDv
{
    [Serializable]
    public class AI2VCUDriveFMsg : Message
    {
        public const string k_RosMessageName = "ads_dv_msgs/AI2VCUDriveF";
        public override string RosMessageName => k_RosMessageName;

        //  Requested front axle torque [0 - 195] Nm
        public ushort front_axle_trq_request_nm;
        //  Front motor speed limit [0 - 4000] rpm
        public ushort front_motor_speed_max_rpm;

        public AI2VCUDriveFMsg()
        {
            this.front_axle_trq_request_nm = 0;
            this.front_motor_speed_max_rpm = 0;
        }

        public AI2VCUDriveFMsg(ushort front_axle_trq_request_nm, ushort front_motor_speed_max_rpm)
        {
            this.front_axle_trq_request_nm = front_axle_trq_request_nm;
            this.front_motor_speed_max_rpm = front_motor_speed_max_rpm;
        }

        public static AI2VCUDriveFMsg Deserialize(MessageDeserializer deserializer) => new AI2VCUDriveFMsg(deserializer);

        private AI2VCUDriveFMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.front_axle_trq_request_nm);
            deserializer.Read(out this.front_motor_speed_max_rpm);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.front_axle_trq_request_nm);
            serializer.Write(this.front_motor_speed_max_rpm);
        }

        public override string ToString()
        {
            return "AI2VCUDriveFMsg: " +
            "\nfront_axle_trq_request_nm: " + front_axle_trq_request_nm.ToString() +
            "\nfront_motor_speed_max_rpm: " + front_motor_speed_max_rpm.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
