//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AdsDv
{
    [Serializable]
    public class AI2VCUSteerMsg : Message
    {
        public const string k_RosMessageName = "ads_dv_msgs/AI2VCUSteer";
        public override string RosMessageName => k_RosMessageName;

        //  Requested steer angle [-27.2 - 27.2] deg
        public short steer_request_deg;

        public AI2VCUSteerMsg()
        {
            this.steer_request_deg = 0;
        }

        public AI2VCUSteerMsg(short steer_request_deg)
        {
            this.steer_request_deg = steer_request_deg;
        }

        public static AI2VCUSteerMsg Deserialize(MessageDeserializer deserializer) => new AI2VCUSteerMsg(deserializer);

        private AI2VCUSteerMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.steer_request_deg);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.steer_request_deg);
        }

        public override string ToString()
        {
            return "AI2VCUSteerMsg: " +
            "\nsteer_request_deg: " + steer_request_deg.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
