//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AdsDv
{
    [Serializable]
    public class VCU2AIBrakeMsg : Message
    {
        public const string k_RosMessageName = "ads_dv_msgs/VCU2AIBrake";
        public override string RosMessageName => k_RosMessageName;

        //  Current hydraulic brake pressure [0 - 100] %
        public byte hyd_pressure_pct;
        //  Requested hydraulic brake pressure [0 - 100] %
        public byte hyd_pressure_request_pct;

        public VCU2AIBrakeMsg()
        {
            this.hyd_pressure_pct = 0;
            this.hyd_pressure_request_pct = 0;
        }

        public VCU2AIBrakeMsg(byte hyd_pressure_pct, byte hyd_pressure_request_pct)
        {
            this.hyd_pressure_pct = hyd_pressure_pct;
            this.hyd_pressure_request_pct = hyd_pressure_request_pct;
        }

        public static VCU2AIBrakeMsg Deserialize(MessageDeserializer deserializer) => new VCU2AIBrakeMsg(deserializer);

        private VCU2AIBrakeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.hyd_pressure_pct);
            deserializer.Read(out this.hyd_pressure_request_pct);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.hyd_pressure_pct);
            serializer.Write(this.hyd_pressure_request_pct);
        }

        public override string ToString()
        {
            return "VCU2AIBrakeMsg: " +
            "\nhyd_pressure_pct: " + hyd_pressure_pct.ToString() +
            "\nhyd_pressure_request_pct: " + hyd_pressure_request_pct.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
