//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AdsDv
{
    [Serializable]
    public class VCU2AIDrivemotordataMsg : Message
    {
        public const string k_RosMessageName = "ads_dv_msgs/VCU2AIDrivemotordata";
        public override string RosMessageName => k_RosMessageName;

        //  Front drive motor temperature [-30 - 225] degC
        public byte motor_f_temp_deg_c;
        //  Rear drive motor temperature [-30 - 225] degC
        public byte motor_r_temp_deg_c;
        //  Front drive motor current [-1638.4 - 1638.35] A
        public short motor_f_curr_0_a05;
        //  Rear drive motor current [-1638.4 - 1638.35] A
        public short motor_r_curr_0_a05;

        public VCU2AIDrivemotordataMsg()
        {
            this.motor_f_temp_deg_c = 0;
            this.motor_r_temp_deg_c = 0;
            this.motor_f_curr_0_a05 = 0;
            this.motor_r_curr_0_a05 = 0;
        }

        public VCU2AIDrivemotordataMsg(byte motor_f_temp_deg_c, byte motor_r_temp_deg_c, short motor_f_curr_0_a05, short motor_r_curr_0_a05)
        {
            this.motor_f_temp_deg_c = motor_f_temp_deg_c;
            this.motor_r_temp_deg_c = motor_r_temp_deg_c;
            this.motor_f_curr_0_a05 = motor_f_curr_0_a05;
            this.motor_r_curr_0_a05 = motor_r_curr_0_a05;
        }

        public static VCU2AIDrivemotordataMsg Deserialize(MessageDeserializer deserializer) => new VCU2AIDrivemotordataMsg(deserializer);

        private VCU2AIDrivemotordataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.motor_f_temp_deg_c);
            deserializer.Read(out this.motor_r_temp_deg_c);
            deserializer.Read(out this.motor_f_curr_0_a05);
            deserializer.Read(out this.motor_r_curr_0_a05);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.motor_f_temp_deg_c);
            serializer.Write(this.motor_r_temp_deg_c);
            serializer.Write(this.motor_f_curr_0_a05);
            serializer.Write(this.motor_r_curr_0_a05);
        }

        public override string ToString()
        {
            return "VCU2AIDrivemotordataMsg: " +
            "\nmotor_f_temp_deg_c: " + motor_f_temp_deg_c.ToString() +
            "\nmotor_r_temp_deg_c: " + motor_r_temp_deg_c.ToString() +
            "\nmotor_f_curr_0_a05: " + motor_f_curr_0_a05.ToString() +
            "\nmotor_r_curr_0_a05: " + motor_r_curr_0_a05.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
