//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AdsDv
{
    [Serializable]
    public class VCU2LOGDynamics1Msg : Message
    {
        public const string k_RosMessageName = "ads_dv_msgs/VCU2LOGDynamics1";
        public override string RosMessageName => k_RosMessageName;

        //  [0 - 255] km/h
        public byte speed_actual_kmh;
        //  [0 - 255] km/h
        public byte speed_target_kmh;
        //  [-64 - 63.5] deg
        public sbyte steer_actual_deg;
        //  [-64 - 63.5] deg
        public sbyte steer_target_deg;
        //  [0 - 100] %
        public byte brake_actual_pct;
        //  [0 - 100] %
        public byte brake_target_pct;
        //  [0 - 100] %
        public byte drive_trq_actual_pct;
        //  [0 - 100] %
        public byte drive_trq_target_pct;

        public VCU2LOGDynamics1Msg()
        {
            this.speed_actual_kmh = 0;
            this.speed_target_kmh = 0;
            this.steer_actual_deg = 0;
            this.steer_target_deg = 0;
            this.brake_actual_pct = 0;
            this.brake_target_pct = 0;
            this.drive_trq_actual_pct = 0;
            this.drive_trq_target_pct = 0;
        }

        public VCU2LOGDynamics1Msg(byte speed_actual_kmh, byte speed_target_kmh, sbyte steer_actual_deg, sbyte steer_target_deg, byte brake_actual_pct, byte brake_target_pct, byte drive_trq_actual_pct, byte drive_trq_target_pct)
        {
            this.speed_actual_kmh = speed_actual_kmh;
            this.speed_target_kmh = speed_target_kmh;
            this.steer_actual_deg = steer_actual_deg;
            this.steer_target_deg = steer_target_deg;
            this.brake_actual_pct = brake_actual_pct;
            this.brake_target_pct = brake_target_pct;
            this.drive_trq_actual_pct = drive_trq_actual_pct;
            this.drive_trq_target_pct = drive_trq_target_pct;
        }

        public static VCU2LOGDynamics1Msg Deserialize(MessageDeserializer deserializer) => new VCU2LOGDynamics1Msg(deserializer);

        private VCU2LOGDynamics1Msg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.speed_actual_kmh);
            deserializer.Read(out this.speed_target_kmh);
            deserializer.Read(out this.steer_actual_deg);
            deserializer.Read(out this.steer_target_deg);
            deserializer.Read(out this.brake_actual_pct);
            deserializer.Read(out this.brake_target_pct);
            deserializer.Read(out this.drive_trq_actual_pct);
            deserializer.Read(out this.drive_trq_target_pct);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.speed_actual_kmh);
            serializer.Write(this.speed_target_kmh);
            serializer.Write(this.steer_actual_deg);
            serializer.Write(this.steer_target_deg);
            serializer.Write(this.brake_actual_pct);
            serializer.Write(this.brake_target_pct);
            serializer.Write(this.drive_trq_actual_pct);
            serializer.Write(this.drive_trq_target_pct);
        }

        public override string ToString()
        {
            return "VCU2LOGDynamics1Msg: " +
            "\nspeed_actual_kmh: " + speed_actual_kmh.ToString() +
            "\nspeed_target_kmh: " + speed_target_kmh.ToString() +
            "\nsteer_actual_deg: " + steer_actual_deg.ToString() +
            "\nsteer_target_deg: " + steer_target_deg.ToString() +
            "\nbrake_actual_pct: " + brake_actual_pct.ToString() +
            "\nbrake_target_pct: " + brake_target_pct.ToString() +
            "\ndrive_trq_actual_pct: " + drive_trq_actual_pct.ToString() +
            "\ndrive_trq_target_pct: " + drive_trq_target_pct.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
