//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AdsDv
{
    [Serializable]
    public class VCU2AIWheelspeedsMsg : Message
    {
        public const string k_RosMessageName = "ads_dv_msgs/VCU2AIWheelspeeds";
        public override string RosMessageName => k_RosMessageName;

        //  Front left wheel speed [0 - 1250] rpm
        public ushort fl_wheel_speed_rpm;
        //  Front right wheel speed [0 - 1250] rpm
        public ushort fr_wheel_speed_rpm;
        //  Rear left wheel speed [0 - 1250] rpm
        public ushort rl_wheel_speed_rpm;
        //  Rear right wheel speed [0 - 1250] rpm
        public ushort rr_wheel_speed_rpm;

        public VCU2AIWheelspeedsMsg()
        {
            this.fl_wheel_speed_rpm = 0;
            this.fr_wheel_speed_rpm = 0;
            this.rl_wheel_speed_rpm = 0;
            this.rr_wheel_speed_rpm = 0;
        }

        public VCU2AIWheelspeedsMsg(ushort fl_wheel_speed_rpm, ushort fr_wheel_speed_rpm, ushort rl_wheel_speed_rpm, ushort rr_wheel_speed_rpm)
        {
            this.fl_wheel_speed_rpm = fl_wheel_speed_rpm;
            this.fr_wheel_speed_rpm = fr_wheel_speed_rpm;
            this.rl_wheel_speed_rpm = rl_wheel_speed_rpm;
            this.rr_wheel_speed_rpm = rr_wheel_speed_rpm;
        }

        public static VCU2AIWheelspeedsMsg Deserialize(MessageDeserializer deserializer) => new VCU2AIWheelspeedsMsg(deserializer);

        private VCU2AIWheelspeedsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.fl_wheel_speed_rpm);
            deserializer.Read(out this.fr_wheel_speed_rpm);
            deserializer.Read(out this.rl_wheel_speed_rpm);
            deserializer.Read(out this.rr_wheel_speed_rpm);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.fl_wheel_speed_rpm);
            serializer.Write(this.fr_wheel_speed_rpm);
            serializer.Write(this.rl_wheel_speed_rpm);
            serializer.Write(this.rr_wheel_speed_rpm);
        }

        public override string ToString()
        {
            return "VCU2AIWheelspeedsMsg: " +
            "\nfl_wheel_speed_rpm: " + fl_wheel_speed_rpm.ToString() +
            "\nfr_wheel_speed_rpm: " + fr_wheel_speed_rpm.ToString() +
            "\nrl_wheel_speed_rpm: " + rl_wheel_speed_rpm.ToString() +
            "\nrr_wheel_speed_rpm: " + rr_wheel_speed_rpm.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
