//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.AdsDv
{
    [Serializable]
    public class VCU2AIDriveFMsg : Message
    {
        public const string k_RosMessageName = "ads_dv_msgs/VCU2AIDriveF";
        public override string RosMessageName => k_RosMessageName;

        //  Current front axle torque [-195 - 195] Nm
        public short front_axle_trq_nm;
        //  Requested front axle torque [0 - 195] Nm
        public ushort front_axle_trq_request_nm;
        //  Maximum front axle drive torque [0 - 195] Nm
        public ushort front_axle_trq_max_nm;

        public VCU2AIDriveFMsg()
        {
            this.front_axle_trq_nm = 0;
            this.front_axle_trq_request_nm = 0;
            this.front_axle_trq_max_nm = 0;
        }

        public VCU2AIDriveFMsg(short front_axle_trq_nm, ushort front_axle_trq_request_nm, ushort front_axle_trq_max_nm)
        {
            this.front_axle_trq_nm = front_axle_trq_nm;
            this.front_axle_trq_request_nm = front_axle_trq_request_nm;
            this.front_axle_trq_max_nm = front_axle_trq_max_nm;
        }

        public static VCU2AIDriveFMsg Deserialize(MessageDeserializer deserializer) => new VCU2AIDriveFMsg(deserializer);

        private VCU2AIDriveFMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.front_axle_trq_nm);
            deserializer.Read(out this.front_axle_trq_request_nm);
            deserializer.Read(out this.front_axle_trq_max_nm);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.front_axle_trq_nm);
            serializer.Write(this.front_axle_trq_request_nm);
            serializer.Write(this.front_axle_trq_max_nm);
        }

        public override string ToString()
        {
            return "VCU2AIDriveFMsg: " +
            "\nfront_axle_trq_nm: " + front_axle_trq_nm.ToString() +
            "\nfront_axle_trq_request_nm: " + front_axle_trq_request_nm.ToString() +
            "\nfront_axle_trq_max_nm: " + front_axle_trq_max_nm.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
