//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class ArdusimpleHeadingMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/ArdusimpleHeading";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public double relpos_n;
        public double relpos_e;
        public double relpos_d;
        public double relpos_length;
        public double relpos_heading;

        public ArdusimpleHeadingMsg()
        {
            this.header = new Std.HeaderMsg();
            this.relpos_n = 0.0;
            this.relpos_e = 0.0;
            this.relpos_d = 0.0;
            this.relpos_length = 0.0;
            this.relpos_heading = 0.0;
        }

        public ArdusimpleHeadingMsg(Std.HeaderMsg header, double relpos_n, double relpos_e, double relpos_d, double relpos_length, double relpos_heading)
        {
            this.header = header;
            this.relpos_n = relpos_n;
            this.relpos_e = relpos_e;
            this.relpos_d = relpos_d;
            this.relpos_length = relpos_length;
            this.relpos_heading = relpos_heading;
        }

        public static ArdusimpleHeadingMsg Deserialize(MessageDeserializer deserializer) => new ArdusimpleHeadingMsg(deserializer);

        private ArdusimpleHeadingMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.relpos_n);
            deserializer.Read(out this.relpos_e);
            deserializer.Read(out this.relpos_d);
            deserializer.Read(out this.relpos_length);
            deserializer.Read(out this.relpos_heading);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.relpos_n);
            serializer.Write(this.relpos_e);
            serializer.Write(this.relpos_d);
            serializer.Write(this.relpos_length);
            serializer.Write(this.relpos_heading);
        }

        public override string ToString()
        {
            return "ArdusimpleHeadingMsg: " +
            "\nheader: " + header.ToString() +
            "\nrelpos_n: " + relpos_n.ToString() +
            "\nrelpos_e: " + relpos_e.ToString() +
            "\nrelpos_d: " + relpos_d.ToString() +
            "\nrelpos_length: " + relpos_length.ToString() +
            "\nrelpos_heading: " + relpos_heading.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
