//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class BoundariesMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/Boundaries";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public ConeArrayMsg[] blue;
        public ConeArrayMsg[] yellow;
        public ConeArrayMsg cones;

        public BoundariesMsg()
        {
            this.header = new Std.HeaderMsg();
            this.blue = new ConeArrayMsg[0];
            this.yellow = new ConeArrayMsg[0];
            this.cones = new ConeArrayMsg();
        }

        public BoundariesMsg(Std.HeaderMsg header, ConeArrayMsg[] blue, ConeArrayMsg[] yellow, ConeArrayMsg cones)
        {
            this.header = header;
            this.blue = blue;
            this.yellow = yellow;
            this.cones = cones;
        }

        public static BoundariesMsg Deserialize(MessageDeserializer deserializer) => new BoundariesMsg(deserializer);

        private BoundariesMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.blue, ConeArrayMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.yellow, ConeArrayMsg.Deserialize, deserializer.ReadLength());
            this.cones = ConeArrayMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.blue);
            serializer.Write(this.blue);
            serializer.WriteLength(this.yellow);
            serializer.Write(this.yellow);
            serializer.Write(this.cones);
        }

        public override string ToString()
        {
            return "BoundariesMsg: " +
            "\nheader: " + header.ToString() +
            "\nblue: " + System.String.Join(", ", blue.ToList()) +
            "\nyellow: " + System.String.Join(", ", yellow.ToList()) +
            "\ncones: " + cones.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
