//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class BoundingBoxArrayMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/BoundingBoxArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public BoundingBoxMsg[] boxes;
        //  dimensions of source image
        public ushort width;
        public ushort height;

        public BoundingBoxArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.boxes = new BoundingBoxMsg[0];
            this.width = 0;
            this.height = 0;
        }

        public BoundingBoxArrayMsg(Std.HeaderMsg header, BoundingBoxMsg[] boxes, ushort width, ushort height)
        {
            this.header = header;
            this.boxes = boxes;
            this.width = width;
            this.height = height;
        }

        public static BoundingBoxArrayMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxArrayMsg(deserializer);

        private BoundingBoxArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.boxes, BoundingBoxMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.width);
            deserializer.Read(out this.height);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.boxes);
            serializer.Write(this.boxes);
            serializer.Write(this.width);
            serializer.Write(this.height);
        }

        public override string ToString()
        {
            return "BoundingBoxArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nboxes: " + System.String.Join(", ", boxes.ToList()) +
            "\nwidth: " + width.ToString() +
            "\nheight: " + height.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
