//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class BoundingBoxMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/BoundingBox";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg a;
        public Geometry.PointMsg b;
        public LabelMsg label;
        public double confidence;

        public BoundingBoxMsg()
        {
            this.a = new Geometry.PointMsg();
            this.b = new Geometry.PointMsg();
            this.label = new LabelMsg();
            this.confidence = 0.0;
        }

        public BoundingBoxMsg(Geometry.PointMsg a, Geometry.PointMsg b, LabelMsg label, double confidence)
        {
            this.a = a;
            this.b = b;
            this.label = label;
            this.confidence = confidence;
        }

        public static BoundingBoxMsg Deserialize(MessageDeserializer deserializer) => new BoundingBoxMsg(deserializer);

        private BoundingBoxMsg(MessageDeserializer deserializer)
        {
            this.a = Geometry.PointMsg.Deserialize(deserializer);
            this.b = Geometry.PointMsg.Deserialize(deserializer);
            this.label = LabelMsg.Deserialize(deserializer);
            deserializer.Read(out this.confidence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.a);
            serializer.Write(this.b);
            serializer.Write(this.label);
            serializer.Write(this.confidence);
        }

        public override string ToString()
        {
            return "BoundingBoxMsg: " +
            "\na: " + a.ToString() +
            "\nb: " + b.ToString() +
            "\nlabel: " + label.ToString() +
            "\nconfidence: " + confidence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
