//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class CarPosMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/CarPos";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg position;
        public float angle;

        public CarPosMsg()
        {
            this.position = new Geometry.PointMsg();
            this.angle = 0.0f;
        }

        public CarPosMsg(Geometry.PointMsg position, float angle)
        {
            this.position = position;
            this.angle = angle;
        }

        public static CarPosMsg Deserialize(MessageDeserializer deserializer) => new CarPosMsg(deserializer);

        private CarPosMsg(MessageDeserializer deserializer)
        {
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            deserializer.Read(out this.angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.angle);
        }

        public override string ToString()
        {
            return "CarPosMsg: " +
            "\nposition: " + position.ToString() +
            "\nangle: " + angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
