//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class ConeMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/Cone";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg position;
        public LabelMsg label;
        public double confidence;

        public ConeMsg()
        {
            this.position = new Geometry.PointMsg();
            this.label = new LabelMsg();
            this.confidence = 0.0;
        }

        public ConeMsg(Geometry.PointMsg position, LabelMsg label, double confidence)
        {
            this.position = position;
            this.label = label;
            this.confidence = confidence;
        }

        public static ConeMsg Deserialize(MessageDeserializer deserializer) => new ConeMsg(deserializer);

        private ConeMsg(MessageDeserializer deserializer)
        {
            this.position = Geometry.PointMsg.Deserialize(deserializer);
            this.label = LabelMsg.Deserialize(deserializer);
            deserializer.Read(out this.confidence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.label);
            serializer.Write(this.confidence);
        }

        public override string ToString()
        {
            return "ConeMsg: " +
            "\nposition: " + position.ToString() +
            "\nlabel: " + label.ToString() +
            "\nconfidence: " + confidence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
