//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class ConeArrayMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/ConeArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public ConeMsg[] cones;

        public ConeArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.cones = new ConeMsg[0];
        }

        public ConeArrayMsg(Std.HeaderMsg header, ConeMsg[] cones)
        {
            this.header = header;
            this.cones = cones;
        }

        public static ConeArrayMsg Deserialize(MessageDeserializer deserializer) => new ConeArrayMsg(deserializer);

        private ConeArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.cones, ConeMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.cones);
            serializer.Write(this.cones);
        }

        public override string ToString()
        {
            return "ConeArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\ncones: " + System.String.Join(", ", cones.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
