//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class EventMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/Event";
        public override string RosMessageName => k_RosMessageName;

        public byte @event;
        public const byte NOT_SELECTED = 0;
        public const byte ACCELERATION = 1;
        public const byte SKIDPAD = 2;
        public const byte AUTOCROSS = 3;
        public const byte TRACK_DRIVE = 4;
        public const byte BRAKE_TEST = 5;
        public const byte INSPECTION = 6;

        public EventMsg()
        {
            this.@event = 0;
        }

        public EventMsg(byte @event)
        {
            this.@event = @event;
        }

        public static EventMsg Deserialize(MessageDeserializer deserializer) => new EventMsg(deserializer);

        private EventMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.@event);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.@event);
        }

        public override string ToString()
        {
            return "EventMsg: " +
            "\n@event: " + @event.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
