//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class GpsDistanceMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/GpsDistance";
        public override string RosMessageName => k_RosMessageName;

        public double abs_distance;
        //  from start to current location
        public double path_distance;
        //  sum of all path segments
        public double est_speed;
        //  estimated speed

        public GpsDistanceMsg()
        {
            this.abs_distance = 0.0;
            this.path_distance = 0.0;
            this.est_speed = 0.0;
        }

        public GpsDistanceMsg(double abs_distance, double path_distance, double est_speed)
        {
            this.abs_distance = abs_distance;
            this.path_distance = path_distance;
            this.est_speed = est_speed;
        }

        public static GpsDistanceMsg Deserialize(MessageDeserializer deserializer) => new GpsDistanceMsg(deserializer);

        private GpsDistanceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.abs_distance);
            deserializer.Read(out this.path_distance);
            deserializer.Read(out this.est_speed);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.abs_distance);
            serializer.Write(this.path_distance);
            serializer.Write(this.est_speed);
        }

        public override string ToString()
        {
            return "GpsDistanceMsg: " +
            "\nabs_distance: " + abs_distance.ToString() +
            "\npath_distance: " + path_distance.ToString() +
            "\nest_speed: " + est_speed.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
