//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class IMUMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/IMU";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        //  Acceleration m/s^2
        public double longitudinal;
        public double lateral;
        public double vertical;
        //  Rate dg/s
        public double yaw;
        public double roll;
        public double pitch;

        public IMUMsg()
        {
            this.header = new Std.HeaderMsg();
            this.longitudinal = 0.0;
            this.lateral = 0.0;
            this.vertical = 0.0;
            this.yaw = 0.0;
            this.roll = 0.0;
            this.pitch = 0.0;
        }

        public IMUMsg(Std.HeaderMsg header, double longitudinal, double lateral, double vertical, double yaw, double roll, double pitch)
        {
            this.header = header;
            this.longitudinal = longitudinal;
            this.lateral = lateral;
            this.vertical = vertical;
            this.yaw = yaw;
            this.roll = roll;
            this.pitch = pitch;
        }

        public static IMUMsg Deserialize(MessageDeserializer deserializer) => new IMUMsg(deserializer);

        private IMUMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.longitudinal);
            deserializer.Read(out this.lateral);
            deserializer.Read(out this.vertical);
            deserializer.Read(out this.yaw);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.pitch);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.longitudinal);
            serializer.Write(this.lateral);
            serializer.Write(this.vertical);
            serializer.Write(this.yaw);
            serializer.Write(this.roll);
            serializer.Write(this.pitch);
        }

        public override string ToString()
        {
            return "IMUMsg: " +
            "\nheader: " + header.ToString() +
            "\nlongitudinal: " + longitudinal.ToString() +
            "\nlateral: " + lateral.ToString() +
            "\nvertical: " + vertical.ToString() +
            "\nyaw: " + yaw.ToString() +
            "\nroll: " + roll.ToString() +
            "\npitch: " + pitch.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
