//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class LabelMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/Label";
        public override string RosMessageName => k_RosMessageName;

        public byte label;
        public const byte BLUE_CONE = 1;
        public const byte YELLOW_CONE = 2;
        public const byte ORANGE_CONE = 3;
        public const byte BIG_ORANGE_CONE = 4;
        public const byte OBSTACLE = 5;
        public const byte HUMAN = 6;
        public const byte WALL = 7;

        public LabelMsg()
        {
            this.label = 0;
        }

        public LabelMsg(byte label)
        {
            this.label = label;
        }

        public static LabelMsg Deserialize(MessageDeserializer deserializer) => new LabelMsg(deserializer);

        private LabelMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.label);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.label);
        }

        public override string ToString()
        {
            return "LabelMsg: " +
            "\nlabel: " + label.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
