//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class LapDataMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/LapData";
        public override string RosMessageName => k_RosMessageName;

        public ushort lap_count;
        public ushort lap_time;

        public LapDataMsg()
        {
            this.lap_count = 0;
            this.lap_time = 0;
        }

        public LapDataMsg(ushort lap_count, ushort lap_time)
        {
            this.lap_count = lap_count;
            this.lap_time = lap_time;
        }

        public static LapDataMsg Deserialize(MessageDeserializer deserializer) => new LapDataMsg(deserializer);

        private LapDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.lap_count);
            deserializer.Read(out this.lap_time);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.lap_count);
            serializer.Write(this.lap_time);
        }

        public override string ToString()
        {
            return "LapDataMsg: " +
            "\nlap_count: " + lap_count.ToString() +
            "\nlap_time: " + lap_time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
