//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class LineMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/Line";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg a;
        public Geometry.PointMsg b;

        public LineMsg()
        {
            this.a = new Geometry.PointMsg();
            this.b = new Geometry.PointMsg();
        }

        public LineMsg(Geometry.PointMsg a, Geometry.PointMsg b)
        {
            this.a = a;
            this.b = b;
        }

        public static LineMsg Deserialize(MessageDeserializer deserializer) => new LineMsg(deserializer);

        private LineMsg(MessageDeserializer deserializer)
        {
            this.a = Geometry.PointMsg.Deserialize(deserializer);
            this.b = Geometry.PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.a);
            serializer.Write(this.b);
        }

        public override string ToString()
        {
            return "LineMsg: " +
            "\na: " + a.ToString() +
            "\nb: " + b.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
