//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class LineArrayMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/LineArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public LineMsg[] blue;
        public LineMsg[] yellow;
        public LineMsg[] orange;

        public LineArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.blue = new LineMsg[0];
            this.yellow = new LineMsg[0];
            this.orange = new LineMsg[0];
        }

        public LineArrayMsg(Std.HeaderMsg header, LineMsg[] blue, LineMsg[] yellow, LineMsg[] orange)
        {
            this.header = header;
            this.blue = blue;
            this.yellow = yellow;
            this.orange = orange;
        }

        public static LineArrayMsg Deserialize(MessageDeserializer deserializer) => new LineArrayMsg(deserializer);

        private LineArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.blue, LineMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.yellow, LineMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.orange, LineMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.blue);
            serializer.Write(this.blue);
            serializer.WriteLength(this.yellow);
            serializer.Write(this.yellow);
            serializer.WriteLength(this.orange);
            serializer.Write(this.orange);
        }

        public override string ToString()
        {
            return "LineArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nblue: " + System.String.Join(", ", blue.ToList()) +
            "\nyellow: " + System.String.Join(", ", yellow.ToList()) +
            "\norange: " + System.String.Join(", ", orange.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
