//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class OdometryMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/Odometry";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public float x;
        public float y;
        public float z;
        public float roll;
        public float pitch;
        public float yaw;

        public OdometryMsg()
        {
            this.header = new Std.HeaderMsg();
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.roll = 0.0f;
            this.pitch = 0.0f;
            this.yaw = 0.0f;
        }

        public OdometryMsg(Std.HeaderMsg header, float x, float y, float z, float roll, float pitch, float yaw)
        {
            this.header = header;
            this.x = x;
            this.y = y;
            this.z = z;
            this.roll = roll;
            this.pitch = pitch;
            this.yaw = yaw;
        }

        public static OdometryMsg Deserialize(MessageDeserializer deserializer) => new OdometryMsg(deserializer);

        private OdometryMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.roll);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.yaw);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.roll);
            serializer.Write(this.pitch);
            serializer.Write(this.yaw);
        }

        public override string ToString()
        {
            return "OdometryMsg: " +
            "\nheader: " + header.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nroll: " + roll.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nyaw: " + yaw.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
