//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class PointArrayMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/PointArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Geometry.PointMsg[] points;

        public PointArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.points = new Geometry.PointMsg[0];
        }

        public PointArrayMsg(Std.HeaderMsg header, Geometry.PointMsg[] points)
        {
            this.header = header;
            this.points = points;
        }

        public static PointArrayMsg Deserialize(MessageDeserializer deserializer) => new PointArrayMsg(deserializer);

        private PointArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.points, Geometry.PointMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.points);
            serializer.Write(this.points);
        }

        public override string ToString()
        {
            return "PointArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\npoints: " + System.String.Join(", ", points.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
