//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class StateMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/State";
        public override string RosMessageName => k_RosMessageName;

        public byte state;
        public const byte INIT = 0; //  Waiting for event to be selected
        public const byte READY = 1; //  Ready for GO signal
        public const byte MAPPING = 2; //  Slow lap for mapping (track drive only)
        public const byte RUNNING = 3; //  Full speed driving
        public const byte FINISHED = 4; //  Finished necessary laps
        public const byte STOPPED = 5; //  Come to a complete stop
        public const byte EMERGENCY = 9; //  Something bad happened; enable emergency brakes

        public StateMsg()
        {
            this.state = 0;
        }

        public StateMsg(byte state)
        {
            this.state = state;
        }

        public static StateMsg Deserialize(MessageDeserializer deserializer) => new StateMsg(deserializer);

        private StateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "StateMsg: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
