//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Obr
{
    [Serializable]
    public class StatusMsg : Message
    {
        public const string k_RosMessageName = "obr_msgs/Status";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public StateMsg state;
        public EventMsg @event;
        //  laps complete, only for track drive event
        //  uint8 becomes bytes in python
        public ushort laps;

        public StatusMsg()
        {
            this.header = new Std.HeaderMsg();
            this.state = new StateMsg();
            this.@event = new EventMsg();
            this.laps = 0;
        }

        public StatusMsg(Std.HeaderMsg header, StateMsg state, EventMsg @event, ushort laps)
        {
            this.header = header;
            this.state = state;
            this.@event = @event;
            this.laps = laps;
        }

        public static StatusMsg Deserialize(MessageDeserializer deserializer) => new StatusMsg(deserializer);

        private StatusMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.state = StateMsg.Deserialize(deserializer);
            this.@event = EventMsg.Deserialize(deserializer);
            deserializer.Read(out this.laps);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.state);
            serializer.Write(this.@event);
            serializer.Write(this.laps);
        }

        public override string ToString()
        {
            return "StatusMsg: " +
            "\nheader: " + header.ToString() +
            "\nstate: " + state.ToString() +
            "\n@event: " + @event.ToString() +
            "\nlaps: " + laps.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
